name: BetterUtilities
version: '${project.version}'
main: org.bettermobs.betterutilities.BetterUtilities
api-version: 1.19
commands:
  trashcan:
    aliases: trash
    description: Opens Trash Can
    permission: bettermobs.trashcan